# Pokemon Tournament Data Entry

For this pair problem, you'll need to load the *pokemon_tournament_data.csv* file into a pandas DataFrame.

**Background:** As a Pokemon researcher, you've received a messy dataset of Pokemon sightings from trainers world wide that includes duplicate entries, missing values, and inconsistent formats. However, some entries are causing the system to crash due to missing information or incorrect formats. As a promising young programmer, you've been asked to help.

**Objective:** Implement a system that validates new Pokedex entries, handling errors and ensuring all necessary information is present. Use the current "known entries" dataset for example entries.

In [2]:
import pandas as pd
pd.read_csv('./pokemon_tournament_data.csv')

     pokemon_id trainer_name pokemon_type pokemon_name seen_time
0            14    Trainer_0        Water    pokémon_0   8:25 PM
1           123    Trainer_1         Fire    POKEMON_1   2:52 PM
2            55    Trainer_2        Water    pokémon_2   4:16 PM
3           114    Trainer_3          NaN    POKEMON_3   1:12 PM
4           120    Trainer_4         Fire    pokémon_4   4:26 PM
..          ...          ...          ...          ...       ...
105         110    Trainer_5          NaN    pokémon_5   6:47 AM
106         136    Trainer_6         Fire    POKEMON_6   5:39 AM
107          48    Trainer_7        Grass    POKEMON_7   6:13 AM
108          41    Trainer_8       Normal    POKEMON_8   9:58 AM
109          13    Trainer_9        Water    POKEMON_9  11:38 PM

[110 rows x 5 columns]

**Issues:**
* Identify any duplicate entries that already exist in the dataset. Use `pokemon_id` and `trainer_name` as the unique identifier.
* If the type of Pokemon is missing, replace the missing value with "Unknown" so the final UI will have something to present to the user.
* The names of the Pokemon are inconsistently formatted. Correct this by ensuring all Pokemon names start with a capital letter followed by lowercase letters.
* All Pokemon IDs should be an integer.


**Task:**
Create a function **validate_pokedex_entry** that accepts a single Pokedex entry (in the form of a dictionary, or a Series) as input (see below).

For each of the above issues:
1. Catch the error as an exception.
2. Log a friendly message.
3. Fix the issue (if it's duplicated already, return an "empty" dictionary).
4. Return the "clean" entry.

**Instructions:**

* <span style="color: darkred;">Implement the **validate_pokedex_entry** function using **`try`-`except`** blocks and **`assert`** statements to validate the data.</span>
* Remember to test your function with different scenarios to ensure it behaves as expected.

In [ ]:
import pandas as pD

In [ ]:
df_pokemon = pd.read_csv('./data/pokemon_tournament_data.csv')

In [ ]:
def validate_pokedex_entry(new_entry):
    # your code here

    print('Function reports errors, and fixes problems ...')

    valid_entry = new_entry  # this is wrong, of course

    return valid_entry

In [ ]:
new_entry = df_pokemon.sample(1).iloc[0]

validate_pokedex_entry(new_entry.to_dict())

Function reports errors, and fixes problems ...

{'pokemon_id': 114,
 'trainer_name': 'Trainer_53',
 'pokemon_type': 'Grass',
 'pokemon_name': 'POKEMON_53',
 'seen_time': '2:15 AM'}